# Generated by Django 3.0.6 on 2020-07-19 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=500)),
                ('originalID', models.CharField(max_length=100)),
                ('fileId', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.CharField(max_length=500)),
                ('directUrl', models.CharField(blank=True, max_length=500, null=True)),
                ('fileSize', models.CharField(blank=True, max_length=100, null=True)),
                ('fileExtension', models.CharField(blank=True, max_length=100, null=True)),
                ('createdDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscribeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GetLink.FileObject')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
