# Generated by Django 3.0.6 on 2020-07-21 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('GetLink', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download', models.CharField(max_length=500)),
                ('realID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GetLink.FileObject')),
            ],
        ),
    ]
