# Generated by Django 3.0.6 on 2020-05-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetLink', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkextract',
            name='directUrl',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='linkextract',
            name='fileId',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
