# Generated by Django 3.0.6 on 2020-07-21 16:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('GetLink', '0002_tempmodels'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempModels',
        ),
    ]
