# Generated by Django 3.0.6 on 2020-05-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetLink', '0002_auto_20200527_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkextract',
            name='fileName',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
