# Generated by Django 3.0.6 on 2020-07-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetLink', '0003_linkextract_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkextract',
            name='fileSize',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
