# Generated by Django 3.0.6 on 2020-07-22 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('GetLink', '0003_delete_tempmodels'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copiedID', models.CharField(max_length=100)),
                ('masterObject',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GetLink.FileObject')),
            ],
        ),
    ]
