# Generated by Django 3.0.6 on 2020-07-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetLink', '0004_linkextract_filesize'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkextract',
            name='fileExtension',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
