# Generated by Django 3.0.6 on 2020-07-23 16:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('GetLink', '0004_tempmodels'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempModels',
        ),
    ]
