# Generated by Django 3.0.6 on 2020-08-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('GetLink', '0005_delete_tempmodels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileobject',
            name='directUrl',
        ),
        migrations.AddField(
            model_name='subscribelist',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
