# Generated by Django 3.0.6 on 2020-07-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetLink', '0005_linkextract_fileextension'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkextract',
            name='publishDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
