# Generated by Django 3.0.6 on 2020-08-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('GetLink', '0006_auto_20200802_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileobject',
            name='counter',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
