# Generated by Django 3.0.6 on 2020-09-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('GetLink', '0007_fileobject_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileobject',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fileobject',
            name='createdDate',
            field=models.DateTimeField(),
        ),
    ]
