# Generated by Django 3.0.6 on 2020-09-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('GetLink', '0008_auto_20200919_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileobject',
            name='createdDate',
            field=models.CharField(max_length=100),
        ),
    ]
