# Generated by Django 3.0.6 on 2020-10-01 06:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('GetLink', '0009_auto_20200919_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileobject',
            old_name='fileId',
            new_name='stotedFileId',
        ),
    ]
